bibliometrics/urls.py
from django.contrib import admin
from django.urls import path, include

# For development
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns
from people.views import AuthorList
from faculties.views import FacultyList, TagList

urlpatterns = [
    # Built-in apps
    path('admin/', admin.site.urls),

    # Custom app needs to be first
    # Includes only built-in URLS
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Project home page
    path('', include('home.urls')),

    # Custom apps
    path('faculties/', include('faculties.urls')),
    path('people/', include('people.urls')),
    path('analytics/', include('analytics.urls')),

    # REST API
    path('api_authors/', AuthorList.as_view()),
    path('api_faculties/', FacultyList.as_view()),
    path('api_tag/', TagList.as_view()),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG: # new

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

faculties/urls.py
from django.urls import path
from . import views

app_name = 'faculties'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('results/', views.results, name='results'),
    path('detail/<int:faculty_id>/', views.detail, name='detail'),
    path('create_faculty/', views.CreateFacultyView.as_view(), name='create_faculty'),
    path('update/<int:pk>/', views.UpdateFacultyView.as_view(), name='update_faculty'),
    path('delete_faculty/<int:pk>', views.DeleteFacultyView.as_view(), name='delete_faculty'),

    path('create_tag/', views.CreateTagView.as_view(), name='create_tag'),
    path('application-submit/', views.application_submit, name='submit-form'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

people/urls.py
from django.urls import path
from . import views


app_name = 'people'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('update-profile/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
    path('auto-update-profile/<int:pk>/', views.auto_profile_update, name='auto-update'),
    # path('create-profile/', views.ProfileUpdateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailsDetailView.as_view(), name='details'),
    path('delete/<int:pk>/', views.ProfileDeleteView.as_view(), name='delete'),

    # AJAX
    path('ajax/get_schools/', views.get_schools, name='get_schools'),
    path('ajax/get_departments/', views.get_departments, name='get_departments')
]

faculties/models.py
from django.db import models
from django.urls import reverse

from faculties.conf import UNI


class Tag(models.Model):
    word = models.CharField(max_length=100, null=True)
    # slug = models.SlugField(max_length=40)

    def __str__(self):
        return self.word

    def get_absolute_url(self):
        return reverse('faculties:index')


class Faculty(models.Model):

    class Meta:
        permissions = (
            ('can_update', 'Can Update'),
            ('can_delete', 'Can Delete'),
        )

    department = models.CharField(max_length=100)
    school = models.CharField(max_length=100)
    university = models.CharField(
        max_length=100,
        choices=UNI,
    )
    science_type = models.ManyToManyField(Tag, blank=True)
    url_site = models.URLField(max_length=250)
    description = models.CharField(max_length=1000, blank=True)

    def get_absolute_url(self):
        return reverse('faculties:detail', kwargs={'faculty_id': self.pk})

    def __str__(self):
        return str(self.department) + ' - ' + str(self.university)

    def get_university(self):
        return self.university

    def get_school(self):
        return self.school

    def get_faculty(self):
        return self.department


class FacultyApplication(Faculty):

    application_date = models.DateTimeField(null=False)
    handled = models.BooleanField(default=False)
    submit_person = models.CharField(max_length=100)

people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from django.dispatch import receiver
from django.db.models.signals import post_save

from faculties.models import Faculty

import datetime


class Author(models.Model):
    # Linked with a built-in User object
    user = models.OneToOneField(User, models.CASCADE, null=True)

    PROFESSOR = '1'
    ASSOCIATE_PROFESSOR = '2'
    ASSISTANT_PROFESSOR = '3'
    LECTURER = '4'
    RANKS = (
        (PROFESSOR, 'Professor'),
        (ASSOCIATE_PROFESSOR, 'Associate Professor'),
        (ASSISTANT_PROFESSOR, 'Assistant Professor'),
        (LECTURER, 'Lecturer')
    )
    rank = models.CharField(
        max_length=100,
        choices=RANKS,
    )
    citedby = models.PositiveIntegerField(default=0)
    faculty = models.ForeignKey(Faculty, null=True, on_delete=models.SET_NULL)
    publications = models.PositiveIntegerField(default=0)
    h_index = models.PositiveIntegerField(default=0,)
    i_10_index = models.PositiveIntegerField(default=0)
    m_index = models.FloatField(default=0)
    max_citations_in_publication = models.PositiveIntegerField(default=0)
    phd_year = models.DateField('Phd Year', null=True)
    google_scholar_url = models.CharField(max_length=500, null=True)
    publication_with_max_citations = models.CharField(max_length=500)
    bio_published = models.BooleanField(default=False)
    profile_photo = models.ImageField(upload_to='profile_pics/', blank=True)

    google_scholar_name = models.CharField(max_length=100, null=False)
    time_to_update = models.PositiveIntegerField(default=0, null=False)
    last_update = models.DateField(default=datetime.date.today)

    def get_absolute_url(self):
        return reverse('people:details', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.user.first_name) + ' ' + str(self.user.last_name)

    # A signal to create an Author object when User signup
    @receiver(post_save, sender=User)
    def update_user_author(sender, instance, created, **kwargs):
        if created:
            Author.objects.create(user=instance)
        instance.author.save()

faculties/forms.py
from django.forms import ModelForm
from .models import Faculty, Tag, FacultyApplication


class FacultyForm(ModelForm):

    class Meta:
        model = Faculty
        fields = [
                'department',
                'school',
                'university',
                'science_type',
                'url_site',
                'description',
        ]


class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = [
            'word',
        ]


class FacultyApplicationForm(ModelForm):
    class Meta:
        model = FacultyApplication
        fields = [
            'department',
            'school',
            'university',
            'science_type',
            'url_site',
            'description'
        ]

faculties/views.py
from django.shortcuts import render, Http404, HttpResponse
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Sum
from django.db.models.functions import Coalesce

import datetime

from guardian.shortcuts import assign_perm
from guardian.mixins import PermissionRequiredMixin

from .models import Faculty, Tag, FacultyApplication
from .forms import FacultyForm, TagForm, FacultyApplicationForm
from people.models import Author

from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import FacultySerializer, TagSerializer


class IndexView(TemplateView):
    template_name = 'faculties/index.html'
    context_object_name = 'faculty_list'

    def get_context_data(self, **kwargs):
        """
        Function that reserves Template data. Retrieve 5 departments with most citations of authors. If there is no data
        to an author 0 added.
        :param kwargs:
        :return: data to the template
        """
        context = super().get_context_data(**kwargs)
        context['faculty_list'] = Faculty.objects.annotate(cited=Coalesce(Sum('author__citedby'), 0)).order_by('-cited')[:5]
        context['faculties_with_most_publications'] = Faculty.objects.annotate(publications=Coalesce(Sum('author__publications'), 0))

        return context


class CreateFacultyView(LoginRequiredMixin, CreateView):
    form_class = FacultyForm
    template_name = 'faculties/create.html'

    def get(self, request, *args, **kwargs):
        tags = Tag.objects.all()
        context = {
            'form': self.form_class,
            'tags': tags,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = FacultyApplicationForm(request.POST)

        if form.is_valid():
            new_application = FacultyApplication()
            new_application.department = form.cleaned_data['department']
            new_application.school = form.cleaned_data['school']
            new_application.university = form.cleaned_data['university']
            new_application.url_site = form.cleaned_data['url_site']

            word = request.POST.getlist('science_type')
            for i in word:
                tag = Tag.objects.get(pk=i)
                new_application.science_type.add(tag)
            new_application.application_date = datetime.datetime.today()
            new_application.submit_person = request.user
            new_application.save()

            return HttpResponse('/application-submit')


def application_submit(request):
    HttpResponse()


class UpdateFacultyView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Faculty
    form_class = FacultyForm
    template_name = 'faculties/update.html'
    permission_required = 'can_update'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['faculty_id'] = self.object.pk
        context['tags'] = Tag.objects.all()

        faculty = Faculty.objects.get(pk=self.object.pk)
        context['faculty'] = faculty
        return context

    def form_valid(self, form):
        if form.save(self):
            return super(UpdateFacultyView, self).form_valid(form)
        else:
            return self

    def post(self, request, *args, **kwargs):
        form = FacultyForm(request.POST)

        for i in form.errors:
            print(i)

        if form.is_valid():
            faculty = Faculty.objects.get(pk=kwargs['pk'])

            faculty.department = form.cleaned_data['department']
            faculty.school = form.cleaned_data['school']
            faculty.university = form.cleaned_data['university']
            faculty.url_site = form.cleaned_data['url_site']
            word = request.POST.getlist('science_type')
            faculty.science_type.clear()
            for i in word:
                tag = Tag.objects.get(pk=i)
                faculty.science_type.add(tag)
            faculty.save()

            # Context to preview details
            context = {
                'faculty': faculty,
                'tags': faculty.science_type.all()
            }
            return render(request, 'faculties/detail.html', context)
        else:
            return render(request, 'faculties/update.html', {'form': form})


class DeleteFacultyView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Faculty
    success_url = reverse_lazy('faculties:index')
    permission_required = 'can_delete'


def results(request):
    if request.method == 'GET':
        user_search = request.GET.get('query')
        try:
            faculties = Faculty.objects.none()
            for search in user_search:
                department = Faculty.objects.filter(department__icontains=search).annotate(cited=Coalesce(Sum('author__citedby'), 0),
                    h_index=Coalesce(Sum('author__h_index'), 0),
                    publications=Coalesce(Sum('author__publications'), 0),)
                school = Faculty.objects.filter(school__icontains=search).annotate(cited=Coalesce(Sum('author__citedby'), 0),
                    h_index=Coalesce(Sum('author__h_index'), 0),
                    publications=Coalesce(Sum('author__publications'), 0),)
                university = Faculty.objects.filter(university__icontains=search).annotate(
                    cited=Coalesce(Sum('author__citedby'), 0),
                    h_index=Coalesce(Sum('author__h_index'), 0),
                    publications=Coalesce(Sum('author__publications'), 0),)
                faculties = faculties | department | school | university
            # If there is no user input return all faculties
            if user_search == '':
                faculties = Faculty.objects.all().annotate(cited=Coalesce(Sum('author__citedby'), 0),
                    h_index=Coalesce(Sum('author__h_index'), 0),
                    publications=Coalesce(Sum('author__publications'), 0),)

        except Faculty.DoesNotExist:
            raise Http404('Faculty doesn \'t exist')
        context = {
            'faculties': faculties.order_by('department'),
        }
        return render(request, 'faculties/results.html', context)


def detail(request, faculty_id):
    try:
        faculty = Faculty.objects.get(id=faculty_id)
        tags = faculty.science_type.all()
        people = Author.objects.filter(faculty=faculty)
        for i in tags:
            print(i)
        context = {
            'faculty': faculty,
            'tags': tags,
            'people': people,
        }
    except Faculty.DoesNotExist:
        raise Http404("Cant retrieve this thing")
    return render(request, 'faculties/detail.html', context)


class CreateTagView(CreateView):
    form_class = TagForm
    template_name = 'faculties/create_tag.html'


class FacultyList(APIView):

    def get(self, request):
        faculties = Faculty.objects.all()
        serializer = FacultySerializer(faculties, many=True)
        return Response(serializer.data)

    def post(self):
        pass


class TagList(APIView):

    def get(self, request):
        tag = Tag.objects.all()
        serializer = TagSerializer(tag, many=True)
        return Response(serializer.data)

    def post(self):
        pass

faculties/templates/faculties/application_form.html
OK

faculties/templates/faculties/create.html
{% extends 'base.html' %}
{% block title %} Add Faculty {% endblock %}

{% block staticfile %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'faculties/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row row-pad">
        <div class="col-sm-4">

        </div>
        <div class="col-sm-4 row-pad">
            <h3>Under construction</h3>
            <div class="card" style="max-width: 35rem;">
                <div class="text-center" style="padding-top:15px">Faculty Registration</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="university">University:</label>
                            <select name="university" class="form-control" id="university">
                                {% for uni in form.university %}
                                    {{ uni }}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="school">School:</label>
                            <input name="school" type="text" class="form-control" id="school">
                        </div>
                        <div class="form-group">
                            <label for="department">Faculty:</label>
                            <input name="department" type="text" class="form-control" id="department">
                        </div>
                        <label for="science_type"> Science types:</label>
                        <div class="float-right element-padding">
                            <a class="img-button" href="{% url 'faculties:create_tag' %}" role="button">
                                <img src="{% static  'faculties/img/add.png' %}" alt="Add Tag">
                            </a>
                        </div>
                        <div class="div_container">
                        <div class="float-left">
                            {% for tag in tags%}
                            <div class="form-check">
                                <!-- Mark checkboxes with previous values -->
                                    <input type="checkbox" name="science_type" class="form-check-input" id="science_type" value="{{ tag.id }}">
                                    <label>{{ tag }}</label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                        <div class="form-group">
                            <label for="url_site">URL:</label>
                            <input name="url_site" type="text" class="form-control" id="url_site">
                        </div>
                        <input class="my_btn" type="submit" value="Add Faculty">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-4">

        </div>
    </div>
</div>

{% endblock %}

faculties/templates/faculties/create_tag.html
{% extends 'base.html' %}
{% block title %} Add Faculty {% endblock %}

{% block body %}
{{ form.non_field_errors }}
<div class="container-fluid" style="float:center">
    <div class="row row-pad">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="card">
                <div class="text-center">Add Tag</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                            <div class="form-group">
                                <label for="word"> Type:</label>
                                <input name="word" type="text" class="form-control" id="word">
                            </div>
                        <input class="my_btn" type="submit" value="Add Tag">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>

{% endblock %}

faculties/templates/faculties/detail.html
{% extends 'base.html' %}

{% block title %} {{ faculty }} details {% endblock %}

{% block staticfile %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'faculties/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
{% endblock %}
{% load guardian_tags %}
{% block body %}
<div class="container-fluid">
    <div class="d-flex justify-content-center fifty">

        <div class="card card-size border-dark">
            <h5 class="card-header">{{ faculty }}</h5>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">School: {{ faculty.school }}</li>
                    <li class="list-group-item">Type:
                        {% for type in tags %}
                        {{ type }}
                        {% endfor %}
                    </li>
                    <li class="list-group-item">URL: <a href=" {{ faculty.url_site }} ">{{ faculty.url_site }}</a></li>
                </ul>
                {% get_obj_perms request.user for faculty as "faculty_perms" %}
                {% if "can_update" in faculty_perms %}
                    <a href="{% url 'faculties:update_faculty' faculty.pk %}" class="my_btn" role="button" style="margin:8px">Faculty Update</a>
                    <a href="{% url 'faculties:delete_faculty' faculty.pk %}" class="my_danger_btn" role="button" style="margin:8px">Faculty Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row-pad table-title">Academic members of the {{ faculty.department }} Department</div>
    <div class="container-fluid">
        <div class="row row-pad">
            <table class="table table-hover table-striped ">
                <thead class="">
                    <th scope="col">#</th>
                    <th scope="col">First name</th>
                    <th scope="col">Last name</th>
                    <th scope="col">Rank</th>
                    <th scope="col" title="Total number of citations">Citations</th>
                    <th scope="col" title="Total number of publications">Publications</th>
                    <th scope="col" title="Number X of publications  with at least X citations">H-Index</th>
                </thead>
                <tbody>
                {% for person in people %}
                <tr data-href="{% url 'people:details' person.id %}" style="cursor: pointer;">
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ person.user.first_name }}</td>
                    <td>{{ person.user.last_name }}</td>
                    <td>{{ person.get_rank_display }}</td>
                    <td>{{ person.citedby }}</td>
                    <td>{{ person.publications }}</td>
                    <td>{{ person.h_index }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function($) {
    $('*[data-href]').on('click', function() {
        window.location = $(this).data("href");
    });
});
</script>
{% endblock %}

faculties/templates/faculties/faculty_confirm_delete.html
{% extends 'base.html' %}
{% block title %} {{ faculty }} delete {% endblock %}

    {% block staticfile %}
	    {% load staticfiles %}
        <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
	    <link rel="stylesheet" type="text/css" href="{% static 'faculties/style.css' %}" />
    {% endblock %}

{% block body %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

faculties/templates/faculties/index.html
{% extends 'base.html' %}
{% block title %} Faculties {% endblock %}
{% block head %}
     <script src="https://cdn.anychart.com/releases/v8/js/anychart-base.min.js"></script>
     <script src="https://cdn.anychart.com/releases/v8/js/anychart-tag-cloud.min.js"></script>
{% endblock %}
{% block staticfile %}
    {% load static %}
     <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
     <link rel="stylesheet" href="{% static 'faculties/style.css' %}" type="text/css" />
{% endblock %}

{% block body %}
<!-- Search bar for university -->
<div class="container-fluid">
     <div class="row-pad">
          <form method="GET" action="{% url 'faculties:results' %}" id="searchbox">
               <!--{% csrf_token %} -->
               <div class="input-group mb-3">
                    <input type="text" name="query" id="searchform" class="form-control" value="{{ request.GET.query}}"
                           placeholder="Search or view all departments..." aria-label="Search" aria-describedby="basic-addon2" oninput="change_to_submit();">
                    <div class="input-group-append">
                    <button id="submit-btn" class="btn btn-outline-secondary" type="submit">View all</button>
                    </div>
               </div>
          </form>
     </div>
</div>

<!-- Main view of faculties -->
<div class="container-fluid">
     <div class="row row-pad">
          <div class="col-md-6">
               <div id="doughnut-holder">
                    <canvas id="citationsDoughnut"></canvas>
               </div>
               <div class="description">
                         The doughnut Chart contains the 5 departments which has the most citations based on the academic
                         member of each one respectively. It is particularly useful for scientific output comparison.
               </div>
          </div>
          <div class="col-md-6">
               <div class="jumbotron" style="background: #dafafa; height: 650px">
                    <div class="card text-center" style="height: 100%;">
                         <div class="card-header">
                              <ul class="nav nav-tabs card-header-tabs">
                                   <li class="nav-item">
                                        <a id="description_tab" class="nav-link active">Departments</a>
                                   </li>
<!--                                   <li class="nav-item">-->
<!--                                        <a id="staff_member_tab" class="nav-link" onclick="changeActiveTab(this, 'staff_member');">Staff Members</a>-->
<!--                                   </li>-->
                              </ul>
                         </div>
                         <div class="card-body">
                              <div class="row" style="height: 100%;">
                                   <div class="col-md-6 text-left" style="border-right: 1px solid #13E8E9;">
                                        {% for faculty in faculty_list %}
                                             <div id="{{ forloop.counter }}" class="departments" onclick="changeDepartment(this);">
                                                  {{ forloop.counter }}. {{ faculty.department }}
                                             </div>
                                        {% endfor %}
                                   </div>
                                   <div class="col-md-6 description-overflow">
                                        <h4>Description</h4>
                                        <p id="description" class="description description-color">
                                             Select a department to preview the description
                                        </p>
                                   </div>
                              </div>

                         </div>
                    </div>
               </div>
          </div>
     </div>
     <div>
          <div class="row">
               <div class="col-md-12">
                    <div id="faculty_wordcloud"></div>
               </div>
          </div>
     </div>
</div>

<script>
     var dataCitations = [{% for faculty in faculty_list %}{{ faculty.cited }}, {% endfor %}];
     var labels = [{% for faculty in faculty_list %}'{{ faculty.department }}', {% endfor %}];

     var ctx = document.getElementById("citationsDoughnut").getContext('2d');
     var myDoughnutChart = new Chart(ctx, {
         type: 'doughnut',
         data: {
              datasets: [{
                  data: dataCitations,
                   // borderColor: ['rgba(75, 192, 192, 1)', 'rgba(192, 0, 0, 1)'],
                   backgroundColor: ['green', 'gray', 'red', 'yellow', 'blue'],
              }],
              labels: labels
          },
         options: {
                    responsive: true,
                    title: {
                        display: true,
                        text: 'Departments with the most citations'
                    }
                }
    });
     document.getElementById("citationsDoughnut").onclick = function(evt)
     {
         var activePoints = myDoughnutChart.getElementsAtEvent(evt);
         if(activePoints.length > 0)
         {
              //get the internal index of slice in pie chart
               var clickedElementindex = activePoints[0]["_index"];

                //get specific label by index
                var label = myDoughnutChart.data.labels[clickedElementindex];

                //get value by index
                var value = myDoughnutChart.data.datasets[0].data[clickedElementindex];


        }
     }
</script>

<script>
    function change_to_submit(){
        var text = document.getElementById('searchform').value;
        if(text){
            document.getElementById('submit-btn').innerHTML = "Submit";
        }
        else{
            document.getElementById('submit-btn').innerHTML = "View all";
        }
    };
</script>

<script>

// List of words
var myWords = [{% for faculty in faculties_with_most_publications %}
                    {
                         x: "{{ faculty.department }}",
                         value: parseInt({{ faculty.publications }}),
                         category: "{{ faculty.university }}"
                    },
               {% endfor %}
               ];
var i;
var max = 0;
var min = 1000000;
for (i=0; i < myWords.length; i++){
     if (parseInt(myWords[i].value) > max){
          max = parseInt(myWords[i].value);
     }
     if (parseInt(myWords[i].value) < min){
          min = parseInt(myWords[i].value);
     }
}
for(i=0; i < myWords.length; i++){
     myWords[i].value = (parseInt(myWords[i].value) - min) / (max - min);
}

anychart.onDocumentReady(function() {
     // create a tag (word) cloud char
     var chart = anychart.tagCloud(myWords);// set a chart title
     chart.title('Departments with most publications');
     // set an array of angles at which the words will be laid out
     chart.angles([0, -45, 45, 30, 60, 90, -90]);
     // enable a color range
     chart.colorRange(true);
     // set the color range length
     chart.colorRange().length('80%');// display the word cloud chart

     chart.container("faculty_wordcloud").draw();
});

</script>

<script>
     function changeDepartment(element) {
          var departments = [
                  {% for faculty in faculty_list %}
                    {
                         name: '{{ faculty.department }}',
                         description: '{{ faculty.description }}',
                    },
                    {% endfor %}]
          document.getElementById('description').innerText = departments[element.id-1].description;
          document.getElementById('description').classList.remove('description-color');
          document.getElementById('description').classList.add('description-select');
     }
</script>
{% endblock %}