bibliometrics/urls.py
from django.contrib import admin
from django.urls import path, include

# For development
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns
from people.views import AuthorList
from faculties.views import FacultyList, TagList

urlpatterns = [
    # Built-in apps
    path('admin/', admin.site.urls),

    # Custom app needs to be first
    # Includes only built-in URLS
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Project home page
    path('', include('home.urls')),

    # Custom apps
    path('faculties/', include('faculties.urls')),
    path('people/', include('people.urls')),
    path('analytics/', include('analytics.urls')),

    # REST API
    path('api_authors/', AuthorList.as_view()),
    path('api_faculties/', FacultyList.as_view()),
    path('api_tag/', TagList.as_view()),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG: # new

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

faculties/urls.py
from django.urls import path
from . import views

app_name = 'faculties'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('results/', views.results, name='results'),
    path('detail/<int:faculty_id>/', views.detail, name='detail'),
    path('create_faculty/', views.CreateFacultyView.as_view(), name='create_faculty'),
    path('update/<int:pk>/', views.UpdateFacultyView.as_view(), name='update_faculty'),
    path('delete_faculty/<int:pk>', views.DeleteFacultyView.as_view(), name='delete_faculty'),

    path('create_tag/', views.CreateTagView.as_view(), name='create_tag'),
    path('application-submit/', views.application_submit, name='submit-form'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

people/urls.py
from django.urls import path
from . import views


app_name = 'people'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('update-profile/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
    path('auto-update-profile/<int:pk>/', views.auto_profile_update, name='auto-update'),
    # path('create-profile/', views.ProfileUpdateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailsDetailView.as_view(), name='details'),
    path('delete/<int:pk>/', views.ProfileDeleteView.as_view(), name='delete'),

    # AJAX
    path('ajax/get_schools/', views.get_schools, name='get_schools'),
    path('ajax/get_departments/', views.get_departments, name='get_departments')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.db.models import Sum
from django.db.models.functions import Coalesce


from django.contrib.auth.models import User
from faculties.models import Faculty
from people.models import Author


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        top_5_departments = Faculty.objects.annotate(cited=Sum('author__citedby')).order_by('-cited')[:5]
        context['top_5_departments'] = top_5_departments
        context['top_5_authors'] = Author.objects.all().order_by('-citedby').exclude(user__is_staff=True).exclude(user__is_active=False)[:5]
        context['top_5_universities'] = top_5_departments.values_list('university', flat=True).annotate(cited=Coalesce(Sum('author__publications'), 0))[:5]
        return context

    def post(self, request):
        user_search = request.POST.get('input')
        user_search = user_search.split()

        faculties = Faculty.objects.none()
        authors = Author.objects.none()
        for search in user_search:
            department = Faculty.objects.filter(department__icontains=search).annotate(cited=Coalesce(Sum('author__citedby'), 0)).order_by('cited')
            school = Faculty.objects.filter(school__icontains=search).annotate(cited=Coalesce(Sum('author__citedby'), 0)).order_by('cited')
            university = Faculty.objects.filter(university__icontains=search).annotate(cited=Coalesce(Sum('author__citedby'), 0)).order_by('cited')
            faculties = faculties | department | school | university

            last = User.objects.filter(last_name__icontains=search).order_by('-author__citedby').exclude(is_staff=True).exclude(is_active=False)
            first = User.objects.filter(first_name__icontains=search).order_by('-author__citedby').exclude(is_staff=True).exclude(is_active=False)
            authors = authors | last | first

        context = {
            'authors': authors.order_by('-author__citedby'),
            'faculties': faculties.order_by('-cited'),
        }
        return render(request, 'home/array_template.html', context)

home/templates/home/array_template.html
{% extends 'base.html' %}
{% block title %} GRep Home {% endblock %}
{% block staticfile %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
{% endblock %}
{% block body %}
<div>
{% if authors or faculties %}
    <div class="container-fluid" style="padding-top:20px;">
        <div class="row">
            <div class="col-md-6" style="border-right: 1px solid black;">
                <div style="text-align:center"><h3>Authors</h3></div>
                    <table class="table table-hover">
                        <thead>
                            <th scope="col">#</th>
                            <th scope="col">First name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Cited by</th>
                        </thead>
                        <tbody>
                        {% for i in authors %}
                        <tr data-href="{% url 'people:details' i.id %}" style="cursor: pointer;">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ i.first_name }}</td>
                            <td>{{ i.last_name }}</td>
                            <td>{{ i.author.citedby }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
            </div>
            <div class="col-md-6">
                <div style="text-align:center"><h3>Faculties</h3></div>
                <table class="table table-hover">
                    <thead>
                        <th scope="col">#</th>
                        <th scope="col">Faculty</th>
                        <th scope="col">School</th>
                        <th scope="col">University</th>
                    </thead>
                    <tbody>
                    {% for fac in faculties %}
                    <tr data-href="{% url 'faculties:detail' fac.id %}" style="cursor: pointer;">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ fac.department }}</td>
                        <td>{{ fac.school }}</td>
                        <td>{{ fac.university}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
{% else %}
    <img src="{% static 'img/404.png' %}" class="float-center not-found-img">
{% endif %}
    <div style="margin: 20px;left: 0; bottom: 0;">
        <a href="{% url 'home:index' %}"><img class="back-btn" src="{% static 'img/back-btn.png' %}">
        </a>
    </div>
</div>

<script>
    jQuery(document).ready(function($) {
        $('*[data-href]').on('click', function() {
        window.location = $(this).data("href");
        });
    });
</script>


{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% block title %} GRep Home {% endblock %}
{% block staticfile %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
{% endblock %}
{% block body %}
<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>

<div id="search-container" class="search-container">
    <div class="container-fluid">
        <!-- https://github.com/VincentGarreau/particles.js -->
        <div id="particles-js"></div>
        <div class="row">
            <div class="col-sm-12 text-center">
                <form method="POST"  style="margin-top: 10%;">
                    {% csrf_token %}
                    <div>
                        <div class="home-title">
                            <symbol id="s-text">
                                <text>Scholarity</text>
                            </symbol>
                        </div>
                    </div>
                    <div class="row-pad">
                        <input type="text" name="input" class="input-simple" placeholder="Search Author or Faculty... e.g. University of Macedonia">
                        <input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;" tabindex="-1" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="search-container" class="search-container" style="overflow:auto;">

    <div class="container-fluid top" style="margin-top: 20%;">
    <div class="row">
        <div class="col-sm-4">
            <div class="jumbotron" style="background: rgb(0,0,0,0)">
                <h3>Departments with most cited authors</h3>
                <hr>
                {% for i in top_5_departments %}
                <ul>
                     <a href="{% url 'faculties:detail' i.id %}"> {{ i }}</a>
                     </br>
                </ul>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-4">
            <div class="jumbotron" style="background: rgb(0,0,0,0)">
                <h3>Top 5 cited Authors</h3>
                <hr>
                {% for i in top_5_authors %}
                <ul>
                     <a href="{% url 'people:details' i.id %}"> {{ i }}</a>
                     </br>
                </ul>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-4">
            <div class="jumbotron" style="background: rgb(0,0,0,0)">
                <h3>Top 5 Universities with most publications</h3>
                <hr>
                {% for i in top_5_universities %}
                <ul>
                     <a> {{ i }}</a>
                     </br>
                </ul>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>



<script>

particlesJS("particles-js", {
  "particles": {
    "number": {
      "value": 200,
      "density": {
        "enable": true,
        "value_area": 800
      }
    },
    "color": {
      "value": "#bfbfbf"
    },
    "shape": {
      "type": "circle",
      "stroke": {
        "width": 0,
        "color": "#bfbfbf"
      },
      "polygon": {
        "nb_sides": 5
      },
      "image": {
        "src": "img/github.svg",
        "width": 100,
        "height": 100
      }
    },
    "opacity": {
      "value": 0.5,
      "random": false,
      "anim": {
        "enable": false,
        "speed": 1,
        "opacity_min": 0.1,
        "sync": false
      }
    },
    "size": {
      "value": 3,
      "random": true,
      "anim": {
        "enable": false,
        "speed": 40,
        "size_min": 0.1,
        "sync": false
      }
    },
    "line_linked": {
      "enable": true,
      "distance": 150,
      "color": "#bfbfbf",
      "opacity": 0.4,
      "width": 1
    },
    "move": {
      "enable": true,
      "speed": 6,
      "direction": "none",
      "random": false,
      "straight": false,
      "out_mode": "out",
      "bounce": false,
      "attract": {
        "enable": false,
        "rotateX": 600,
        "rotateY": 1200
      }
    }
  },
  "interactivity": {
    "detect_on": "canvas",
    "events": {
      "onhover": {
        "enable": true,
        "mode": "grab"
      },
      "onclick": {
        "enable": true,
        "mode": "push"
      },
      "resize": true
    },
    "modes": {
      "grab": {
        "distance": 140,
        "line_linked": {
          "opacity": 1
        }
      },
      "bubble": {
        "distance": 400,
        "size": 40,
        "duration": 2,
        "opacity": 8,
        "speed": 3
      },
      "repulse": {
        "distance": 200,
        "duration": 0.4
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true
});
</script>
<script>
/* ---- stats.js config ---- */

    var count_particles, stats, update;
    stats = new Stats;
    stats.setMode(0);
    stats.domElement.style.position = 'absolute';
    stats.domElement.style.left = '0px';
    stats.domElement.style.top = '0px';
    document.body.appendChild(stats.domElement);
    count_particles = document.querySelector('.js-count-particles');
    update = function() {
        stats.begin();
        stats.end();
        if (window.pJSDom[0].pJS.particles && window.pJSDom[0].pJS.particles.array) {
            count_particles.innerText = window.pJSDom[0].pJS.particles.array.length;
        }
        requestAnimationFrame(update);
    };
    requestAnimationFrame(update);
</script>
<!--
<script>
    var lastScrollTop = 40;
    var delayInMilliseconds = 1000;
    window.addEventListener("wheel", event => {
    var st = window.pageYOffset || document.documentElement.scrollTop;
    if (st > lastScrollTop){
        window.scrollTo(40,document.body.scrollHeight, "slow");
    } else {
        window.scrollTo(0,0);
    }
    lastScrollTop = st <= 0 ? 0 : st;
    });
</script>
-->
<!-- na prosthesw koumpi gia na katevenei -->
<script>
    $('a[href^="#"]').on('click', function(event) {
    var target = $( $(this).attr('href') );
    if( target.length ) {
        event.preventDefault();
        $('html, body').animate({
            scrollTop: target.offset().top,
            scrollBottom: target.offset().bottom
        }, 3000);
    } });
</script>
{% endblock %}