accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    # path('password_change/', auth_views.password_change, name='login'),
]

bibliometrics/urls.py
from django.contrib import admin
from django.urls import path, include

# For development
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns
from people.views import AuthorList
from faculties.views import FacultyList, TagList

urlpatterns = [
    # Built-in apps
    path('admin/', admin.site.urls),

    # Custom app needs to be first
    # Includes only built-in URLS
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Project home page
    path('', include('home.urls')),

    # Custom apps
    path('faculties/', include('faculties.urls')),
    path('people/', include('people.urls')),
    path('analytics/', include('analytics.urls')),

    # REST API
    path('api_authors/', AuthorList.as_view()),
    path('api_faculties/', FacultyList.as_view()),
    path('api_tag/', TagList.as_view()),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG: # new

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

faculties/urls.py
from django.urls import path
from . import views

app_name = 'faculties'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('results/', views.results, name='results'),
    path('detail/<int:faculty_id>/', views.detail, name='detail'),
    path('create_faculty/', views.CreateFacultyView.as_view(), name='create_faculty'),
    path('update/<int:pk>/', views.UpdateFacultyView.as_view(), name='update_faculty'),
    path('delete_faculty/<int:pk>', views.DeleteFacultyView.as_view(), name='delete_faculty'),

    path('create_tag/', views.CreateTagView.as_view(), name='create_tag'),
    path('application-submit/', views.application_submit, name='submit-form'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

people/urls.py
from django.urls import path
from . import views


app_name = 'people'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('update-profile/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
    path('auto-update-profile/<int:pk>/', views.auto_profile_update, name='auto-update'),
    # path('create-profile/', views.ProfileUpdateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailsDetailView.as_view(), name='details'),
    path('delete/<int:pk>/', views.ProfileDeleteView.as_view(), name='delete'),

    # AJAX
    path('ajax/get_schools/', views.get_schools, name='get_schools'),
    path('ajax/get_departments/', views.get_departments, name='get_departments')
]

bibliometrics/templates/bibliometrics/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} Bibliometrics {% endblock %}</title>
    {% block head %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CDN declarations -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"
            integrity="sha256-c9vxcXyAG4paArQG3xk6DjyW/9aHxai2ef9RpMWO44A=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    {% block staticfile %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a class="navbar-brand abs" href="/">
        <img class="logo" src="{% static '/img/logo.png' %}">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="collapsingNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/analytics">Analytics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/faculties">Faculties</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/people">People</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item" style="border: 1px solid #FFC0CB; margin:-1px;">
                <a class="nav-link" href="{% url 'people:update' user.id%}"><span
                        style="padding-right:10px;">{{ user }}</span>
                    {% if user.author.profile_photo %}
                    <img class="float-center menu-bar-picture" src="{{ user.author.profile_photo.url }}">
                    {% else %}
                    <img class="float-center menu-bar-picture" src="{% static 'img/no_picture.png' %}">
                    {% endif %}
                </a>
            </li>
            <li class="nav-item" style="padding-top:4px; padding-bottom:3px;">
                <a class="nav-link" href="{% url 'logout' %}">logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<!-- Body -->
<div class="main-container">
    {% block body %}
    <div class="container-fluid">

    </div>
    {% endblock %}
</div>
<!-- Footer -->
{% block footer %}
<footer class="page-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 footer-border footer-space footer-space">
                <a class="footer-title">About</a>
                <p>
                    Scholarity is a web-app which provide analytics <br/>
                    about the universities and academic staff of the<br/>
                    country. Our goal is to provide a clear view of <br/>
                    the ...
                </p>
            </div>
            <div class="col-md-4 footer-space footer-border">
                <a class="footer-title">Contact</a>
                <div>
                    <div>Email: alouvoul@hotmail.com</div>
                    <div>Thessaloniki 54643, Greece</div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-md-6 footer-register-text">
                        Register for free
                    </div>
                    <div class="col-md-6 text-center">
                        <a class="btn btn-danger footer-button" type="button" href="{% url 'accounts:signup' %}">SIGN UP!</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 footer-space">
                <a class="footer-title">Useful Links</a>
                <div class="links-footer-button">
                    <a href="#">API</a><br/>
                    <a href="{% url 'faculties:create_faculty' %}">Register a faculty</a><br/>
                    <a href="/">Home</a><br/>
                    <a href="/analytics">Analytics</a><br/>
                    <a href="/faculties">Faculties</a><br/>
                    <a href="/people">People</a>
                </div>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-12" style="background-color: #343a40;">
                <!-- Copyright -->
                <div class="footer-copyright py-3"> Copyright© 2019 - <script>document.write(new Date().getFullYear())</script>:
                    <a href="https://gitlab.com/alouvoul/thesis"> Scholarity</a>
                </div>
            </div>
        </div>
    </div>
</footer>
{% endblock %}
</body>
</html>