bibliometrics/urls.py
from django.contrib import admin
from django.urls import path, include

# For development
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns
from people.views import AuthorList
from faculties.views import FacultyList, TagList

urlpatterns = [
    # Built-in apps
    path('admin/', admin.site.urls),

    # Custom app needs to be first
    # Includes only built-in URLS
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Project home page
    path('', include('home.urls')),

    # Custom apps
    path('faculties/', include('faculties.urls')),
    path('people/', include('people.urls')),
    path('analytics/', include('analytics.urls')),

    # REST API
    path('api_authors/', AuthorList.as_view()),
    path('api_faculties/', FacultyList.as_view()),
    path('api_tag/', TagList.as_view()),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG: # new

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

faculties/urls.py
from django.urls import path
from . import views

app_name = 'faculties'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('results/', views.results, name='results'),
    path('detail/<int:faculty_id>/', views.detail, name='detail'),
    path('create_faculty/', views.CreateFacultyView.as_view(), name='create_faculty'),
    path('update/<int:pk>/', views.UpdateFacultyView.as_view(), name='update_faculty'),
    path('delete_faculty/<int:pk>', views.DeleteFacultyView.as_view(), name='delete_faculty'),

    path('create_tag/', views.CreateTagView.as_view(), name='create_tag'),
    path('application-submit/', views.application_submit, name='submit-form'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

people/urls.py
from django.urls import path
from . import views


app_name = 'people'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('update-profile/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
    path('auto-update-profile/<int:pk>/', views.auto_profile_update, name='auto-update'),
    # path('create-profile/', views.ProfileUpdateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailsDetailView.as_view(), name='details'),
    path('delete/<int:pk>/', views.ProfileDeleteView.as_view(), name='delete'),

    # AJAX
    path('ajax/get_schools/', views.get_schools, name='get_schools'),
    path('ajax/get_departments/', views.get_departments, name='get_departments')
]

people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from django.dispatch import receiver
from django.db.models.signals import post_save

from faculties.models import Faculty

import datetime


class Author(models.Model):
    # Linked with a built-in User object
    user = models.OneToOneField(User, models.CASCADE, null=True)

    PROFESSOR = '1'
    ASSOCIATE_PROFESSOR = '2'
    ASSISTANT_PROFESSOR = '3'
    LECTURER = '4'
    RANKS = (
        (PROFESSOR, 'Professor'),
        (ASSOCIATE_PROFESSOR, 'Associate Professor'),
        (ASSISTANT_PROFESSOR, 'Assistant Professor'),
        (LECTURER, 'Lecturer')
    )
    rank = models.CharField(
        max_length=100,
        choices=RANKS,
    )
    citedby = models.PositiveIntegerField(default=0)
    faculty = models.ForeignKey(Faculty, null=True, on_delete=models.SET_NULL)
    publications = models.PositiveIntegerField(default=0)
    h_index = models.PositiveIntegerField(default=0,)
    i_10_index = models.PositiveIntegerField(default=0)
    m_index = models.FloatField(default=0)
    max_citations_in_publication = models.PositiveIntegerField(default=0)
    phd_year = models.DateField('Phd Year', null=True)
    google_scholar_url = models.CharField(max_length=500, null=True)
    publication_with_max_citations = models.CharField(max_length=500)
    bio_published = models.BooleanField(default=False)
    profile_photo = models.ImageField(upload_to='profile_pics/', blank=True)

    google_scholar_name = models.CharField(max_length=100, null=False)
    time_to_update = models.PositiveIntegerField(default=0, null=False)
    last_update = models.DateField(default=datetime.date.today)

    def get_absolute_url(self):
        return reverse('people:details', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.user.first_name) + ' ' + str(self.user.last_name)

    # A signal to create an Author object when User signup
    @receiver(post_save, sender=User)
    def update_user_author(sender, instance, created, **kwargs):
        if created:
            Author.objects.create(user=instance)
        instance.author.save()

people/forms.py
from django import forms
from people.models import Author
from faculties.models import Faculty


class AuthorForm(forms.ModelForm):

    department = forms.CharField()
    university = forms.CharField()
    school = forms.CharField()

    class Meta:
        model = Author
        fields = [
            'citedby',
            'rank',
            'publications',
            'h_index',
            'i_10_index',
            'm_index',
            'max_citations_in_publication',
            'phd_year',
            'google_scholar_url',
            'publication_with_max_citations',
            'bio_published',
            'profile_photo',
        ]
        help_texts = {
            'citedby': 'Total umber of citations',
            'h_index': 'N Publications with at least N citations',
            'i_10_index': 'Number of publications with 10 or more citations',
            'm_index': 'Metric of h/years',
            'max_citations_in_publication': 'Max number of citations in a single publication'
        }

    def save(self, commit=True):
        faculty = Faculty.objects.values(
            department=self.cleaned_data['department'],
            school=self.cleaned_data['school'],
            university=self.cleaned_data['university'],
        )
        print("Save method")
        print(faculty.department)
        self.cleaned_data['faculty'] = faculty.id
        return super(AuthorForm, self).save(commit)


class AutoUpdateForm(forms.Form):
    auto_update = forms.CharField(max_length=100)
    checktime = forms.IntegerField(min_value=0)
    repeat_update = forms.BooleanField(required=False)


class DeleteAuthorForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)

people/views.py
import scholarly
import threading
import time
import datetime

from datetime import timedelta
from django.shortcuts import render, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.db.utils import OperationalError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from .models import Author
from faculties.models import Faculty
from .forms import AuthorForm, AutoUpdateForm, DeleteAuthorForm

# REST API #
from rest_framework.views import APIView
from .serializers import AuthorSerializer
from rest_framework.response import Response


def index(request):

    top_10_authors = Author.objects.all().order_by('-citedby').exclude(user__is_staff=True).exclude(user__is_active=False)[:10]
    context = {
        'people': top_10_authors,
    }
    return render(request, 'people/index.html', context)


class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'people/update_profile.html'

    def post(self, request, *args, **kwargs):
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            faculty = None
            try:
                faculty = Faculty.objects.get(
                    department=form.cleaned_data['department'],
                    school=form.cleaned_data['school'],
                    university=form.cleaned_data['university'],
                )
            except:
                print('Faculty is not exists')
            if faculty is not None:
                author = Author.objects.get(pk=request.user.id)
                author.rank = form.cleaned_data['rank']
                author.publications = form.cleaned_data['publications']
                author.citedby = form.cleaned_data['citedby']
                author.h_index = form.cleaned_data['h_index']
                author.i_10_index = form.cleaned_data['i_10_index']
                author.m_index = form.cleaned_data['m_index']
                author.max_citations_in_publication = form.cleaned_data['max_citations_in_publication']
                author.phd_year = form.cleaned_data['phd_year']
                author.google_scholar_url = form.cleaned_data['google_scholar_url']
                author.publication_with_max_citations = form.cleaned_data['publication_with_max_citations']
                author.bio_published = form.cleaned_data['bio_published']
                author.profile_photo = form.cleaned_data['profile_photo']
                author.faculty = faculty

                # Update Last update value
                author.last_update = datetime.date.today()
                # User in detail template to check who update last time
                author.google_scholar_name = ""
                author.save()

                return render(request, 'people/details.html', {'object': author})
        context = {
            'form': form,
            'object': request.user.author,
            'university': Faculty.objects.values_list('university', flat=True).distinct(),
            'school': Faculty.objects.values_list('school', flat=True).distinct(),
            'department': Faculty.objects.values_list('department', flat=True).distinct()
        }
        print(form.errors)
        return render(request, 'people/update_profile.html', context)

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        university = Faculty.objects.values_list('university', flat=True).distinct()
        # school = Faculty.objects.values_list('school', flat=True).distinct()
        # faculty = Faculty.objects.values_list('department', flat=True).distinct()

        # context['faculties'] = Faculty.objects.all()
        context['university'] = university
        # context['school'] = school
        # context['department'] = faculty
        return context


def get_schools(request):
    from django.http import JsonResponse
    university = request.GET.get('university')

    schools = Faculty.objects.filter(university=university).values_list('school', flat=True).distinct()
    data = {
        'schools': list(schools)
    }
    return JsonResponse(data)


def get_departments(request):
    from django.http import JsonResponse
    school = request.GET.get('school')
    university = request.GET.get('university')

    # Filter university & school because if retrieve only school probably there are a few schools with the same name
    departments = Faculty.objects.filter(school=school, university=university).values_list('department', flat=True).distinct()
    data = {
        'departments': list(departments)
    }

    return JsonResponse(data)


def auto_profile_update(request, pk):

    if request.method == 'POST':
        form = AutoUpdateForm(request.POST)
        print(form.errors)
        if form.is_valid():
            name = request.POST.get("auto_update")
            check_time = request.POST.get("checktime")
            repeat_update = request.POST.get("repeat_update")

            if check_time is None:
                check_time = 0
            check_time = int(check_time)

            author = online_search(name, pk)
            if author:
                author.google_scholar_name = name
                author.time_to_update = check_time
                author.save()
                return HttpResponseRedirect(reverse('people:details', kwargs={'pk': pk}))
            else:
                msg = 'Service unavailable! Please try again later.'
                form.add_error('auto_update', msg)
                return render(request, 'people/auto_update.html', {'form': form})
        else:
            print('Is not valid')
            return render(request, 'people/auto_update.html', {'form': form})
    else:
        form = AutoUpdateForm()
        return render(request, 'people/auto_update.html', {'form': form})


def online_search(name, pk):
    try:
        search = scholarly.scholarly.search_author(name)
        author = Author.objects.get(pk=pk)

        person_info = next(search).fill()
        print(person_info.name)
        print(person_info.citedby)

        author.citedby = person_info.citedby

        author.publications = len(person_info.publications)  # number of publications
        author.h_index = person_info.hindex
        author.i_10_index = person_info.i10index
        author.m_index = "{0:.2f}".format(float(person_info.hindex) / float(len(person_info.cites_per_year)))
        publication_info = person_info.publications[0].fill()
        author.max_citations_in_publication = sum(publication_info.cites_per_year.values())
        author.publication_with_max_citations = publication_info.bib['title']
        # Update Last update value
        author.last_update = datetime.date.today()
        return author
    except:
        return False


def time_interval_update():
    while True:
        time.sleep(86400)   # Repeat every day
        try:
            users_to_update = Author.objects.filter(time_to_update__gte=1).values_list('id', flat=True)
        except OperationalError:
            users_to_update = None

        if users_to_update is not None:
            for i in users_to_update:
                author = Author.objects.get(id=i)
                if its_time_to_update(author.last_update, author.time_to_update):
                    online_search(author.google_scholar_name, author.pk)


def its_time_to_update(last_update, time_to_update):
    if last_update < datetime.date.today():
        if last_update + timedelta(days=time_to_update) < datetime.date.today():
            return True
    else:
        return False


class ProfileDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Author
    success_url = reverse_lazy('people:index')
    template_name = 'people/author_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileDeleteView, self).get_context_data(**kwargs)
        context['form'] = DeleteAuthorForm()
        return context

    def delete(self, request, *args, **kwargs):
        from django.contrib.auth import authenticate
        from django.contrib import messages

        form = DeleteAuthorForm(request.POST)
        if form.is_valid():
            username = request.user.username
            password = form.cleaned_data.get('password')
            authenticated = authenticate(username=username, password=password)

            if authenticated:
                author_id = request.user.id
                delete_author = Author.objects.get(id=author_id)
                delete_user = User.objects.get(id=author_id)

                delete_user.delete()
                delete_author.delete()
                return HttpResponseRedirect(self.success_url)

        messages.add_message(request, messages.ERROR, 'Could not authenticate your profile')
        return render(request, self.template_name, {'object': request.user})


def results(request):
    """
    TODO Add some logic to find the correct name
    :param request:
    :return:
    """
    if request.method == 'GET':
        user_search = request.GET.get('query')
        try:
            authors = User.objects.none()
            for search in user_search:
                last = User.objects.filter(last_name__icontains=search).order_by('author__citedby').exclude(is_staff=True).exclude(is_active=False)
                first = User.objects.filter(first_name__icontains=search).order_by('author__citedby').exclude(is_staff=True).exclude(is_active=False)
                authors = authors | last | first
            if user_search == '':
                authors = User.objects.all().exclude(is_staff=True).exclude(is_active=False)
        except User.DoesNotExist:
            raise Http404('Author doesn \'t exist')
        context = {
            'authors': authors.order_by('last_name'),
        }

people/templates/people/author_confirm_delete.html
{% extends 'base.html' %}
{% block title %} Delete {{ object }} {% endblock %}
{% block staticfile %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'people/style.css' %}" type="text/css" />
{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="d-flex justify-content-center row-pad">
        <div class="card cards-size">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for mes in messages %}
                        <div class="alert alert-danger">
                            <strong>{{ mes|escape }}</strong>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div>Are you sure you want to delete your account" {{ object }}"?</div>
                    </div>
                    <div class="form-group text-center row-pad">
                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" minlength="8">
                    </div>
                    <div class="container-fluid">
                        <div class="row row-pad text-center">
                            <input class="btn btn-outline-danger" type="submit" value="Confirm">
                            <a class="btn btn-outline-dark" href="{% url 'people:update' object.id %} " id="cancel" name="cancel"> Cancel</a>
                        </div>
                    </div>
                </form>
             </div>
        </div>
    </div>
</div>
{% endblock %}

people/templates/people/create_profile.html
{% extends 'base.html' %}

{% block title%} {{ user.name }} {% endblock %}

{% block body %}

{{ user }}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>


{% endblock %}

people/templates/people/results.html
{% extends 'base.html' %}

{% block title %} Results {% endblock %}

{% block staticfile %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'people/style.css' %}" type="text/css"/>
{% endblock %}
{% block body %}
{% if authors %}
    <div id="table-content" style="overflow: auto;">
        <table class="table table-hover table-striped" >
            <thead class="array-results-templates">
            <tr>
                <th scope="col">#</th>
                <th scope="col">First name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Cited by</th>
                <th scope="col">H-Index</th>
                <th scope="col">Max citations in publication</th>
            </tr>
            </thead>
            <tbody>
            {% for fac in authors %}
            <tr data-href="{% url 'people:details' fac.id %}">
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ fac.first_name }}</td>
                <td>{{ fac.last_name }}</td>
                <td>{{ fac.author.citedby }}</td>
                <td>{{ fac.author.h_index }}</td>
                <td>{{ fac.author.max_citations_in_publication }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <a id="downloadPDF" type="button" style="position: fixed; bottom: 50px; right: 50px;">
        <img src="{% static 'img/pdf.png' %}" alt="Print to PDF" style="height:50px; width:50px;">
    </a>
{% else %}
    <img src="{% static 'img/404.png' %}" class="float-center not-found-img">
{% endif %}
    <div style="margin: 20px;left: 0; bottom: 0;">
        <a href="{% url 'people:index' %}"><img class="back-btn" src="{% static 'img/back-btn.png' %}">
        </a>
    </div>

<script>
    jQuery(document).ready(function($) {
    $('*[data-href]').on('click', function() {
        window.location = $(this).data("href");
    });
});
</script>
<script>
    $('#downloadPDF').click(function () {
    domtoimage.toPng(document.getElementById('table-content'))
        .then(function (blob) {
            var pdf = new jsPDF('l', 'pt', [$('#table-content').width(), $('#table-content').height()]);

            pdf.addImage(blob, 'PNG', 0, 0, $('#table-content').width(), $('#table-content').height());
            pdf.save("search-table.pdf");

            that.options.api.optionsChanged();
        });
    });
</script>

{% endblock %}

people/templates/people/update_profile.html
{% extends 'base.html' %}

{% block title%} {{ user.name }} {% endblock %}
{% block staticfile %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'people/style.css' %}" type="text/css" />
{% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row row-pad">
        <div class="col-sm-4">

        </div>
        <div class="col-sm-4">
            <div class="card cards-size border-dark">
                <div class="text-center card-text">
                    <h3>Account Update</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">Connect your account with Google Scholar?</div>
                        <div class="col-lg-6">
                            <a name="auto-update-button" type="button" href="{% url 'people:auto-update' user.id %}" class="my_btn" style="float: right;">Auto update</a>
                        </div>
                    </div>
                    <br >
                    <hr class="row-pad">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div id="university" class="form-group">
                            <label for="university">University:</label>
                            <select id="university-select" name="university" class="form-control js-get_schools">
                                {% for uni in university %}
                                <option value="{{ uni }}">{{ uni }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            {% for error in form.school.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            <label for="school">School:</label>
                            <select name="school" class="form-control" id="school-select">
                                {% for sch in school %}
                                <option>{{ sch }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            {% for error in form.faculty.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            <label for="department">Faculty:</label>
                            <select name="department" class="form-control" id="department-select">
                            {% for fac in department %}
                                <option>{{ fac }}</option>
                            {% endfor %}
                            </select>
                        </div>
                        <div>
                            {% for error in form.rank.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            <label for="rank">Academic Rank:</label>
                            <select name="rank" class="form-control" id="rank">
                            {% for value, text in form.rank.field.choices %}
                                <option value="{{ value }}" {% if object.rank == value %} selected="selected"{% endif %}>{{ text }}</option>
                            {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            {% for error in form.citedby.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            <label for="citedby">Total citations:</label>
                            <input name="citedby" type="text" class="form-control" id="citedby" value="{{ object.citedby }}">
                        </div>
                        <div class="form-group">
                            {% for error in form.publications.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            <label for="publications">Publications:</label>
                            <input name="publications" type="text" class="form-control" id="publications" value="{{ object.publications }}">
                        </div>
                        <div class="form-group">
                            <label for="h_index">H-Index:</label>
                            <input name="h_index" type="number" class="form-control" id="h_index" min="0" value="{{ object.h_index }}">
                        </div>
                        <div class="form-group">
                            <label for="i_10_index">I10-Index:</label>
                            <input name="i_10_index" type="number" class="form-control" id="i_10_index" min="0" value="{{ object.i_10_index }}">
                        </div>
                        <div class="form-group">
                            <label for="m_index">M-Index:</label>
                            <input name="m_index" type="number" class="form-control" id="m_index" min="0.0" value="{{ object.m_index }}" step=0.01>
                        </div>
                        <div class="form-group">
                            <label for="max_citations_in_publication">Max citations in paper:</label>
                            <input name="max_citations_in_publication" type="number" class="form-control" id="max_citations_in_publication" min="0" value="{{ object.max_citations_in_publication }}">
                        </div>
                        <div class="form-group">
                            <label for="phd_year">Phd year:</label>
                            <input name="phd_year" type="date" class="form-control" id="phd_year" value='{{ object.phd_year|date:"Y-m-d" }}'>
                            {% for error in form.phd_year.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="google_scholar_url">Google scholar URL:</label>
                            <input name="google_scholar_url" type="text" class="form-control" id="google_scholar_url" value="{{ object.google_scholar_url }}">
                        </div>
                        <div class="form-group">
                            {% for error in form.publication_with_max_citations.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            <label for="publication_with_max_citations">Most cited paper:</label>
                            <input name="publication_with_max_citations" type="text" class="form-control" id="publication_with_max_citations" value="{{ object.publication_with_max_citations }}">
                        </div>
                        <div class="form-group">
                            <label for="bio_published">Published Bio:</label>
                            <input name="bio_published" type="checkbox" class="form-control" id="bio_published" value="{{ object.bio_published }}">
                        </div>
                        <hr>

                            <span>Profile Photo</span><br>
                            {{ form.profile_photo }}
                        <div class="row-pad">
                            <button name="manual-update" type="submit" class="my_btn" value="Update">Submit</button>
                            <a href="{% url 'people:delete' user.id %}" type="button" class="my_danger_btn">Delete Account</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#university-select").change(function () {
        var university = $(this).val();

        $.ajax({
      		url :  "{% url 'people:get_schools' %}",
      		data : {
      		    'university': university
      		},
      		success : function(response){
                select = document.getElementById('school-select');
                select.options.length = 0;
                console.log(response.schools);
                var i = 0;
                for (i = 0; i < response.schools.length; i++) {
                    select.options[i] = new Option(response.schools[i], response.schools[i]);
                }
      		},
      		error : function(response){
      			alert('Error occurred')
      		}
      	});
    });

</script>
<script type="text/javascript">

        $("#school-select").change(function () {
        var school = $(this).val();

        $.ajax({
      		url :  "{% url 'people:get_departments' %}",
      		data : {
      		    'school': school,
      		    'university': document.getElementById('university-select').value,
      		},
      		success : function(response){
                select = document.getElementById('department-select');
                select.options.length = 0;
                console.log(response.schools);
                var i = 0;
                for (i = 0; i < response.departments.length; i++) {
                    select.options[i] = new Option(response.departments[i], response.departments[i]);
                }
      		},
      		error : function(response){
      			alert('Error occured')
      		}
      	});
    });
</script>
{% endblock %}